# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"
architect:
  allowed-worlds:
    - "world"
bailiff:
  claims:
    level-1: 20 # Additional claims added by the bailiff.
    level-2: 40
    level-3: 80
  upgrade-cost:
    level-1: 20000 # Cost to hire bailiff.
    level-2: 40000
    level-3: 80000
treasurer:
  limit:
    level-0: 10000 # Town bank limit without a treasurer.
    level-1: 25000 # Town bank limit with a level 1 treasurer.
    level-2: 50000
    level-3: 100000
    level-4: 200000
  upgrade-cost:
    level-1: 5000
    level-2: 10000
    level-3: 20000
    level-4: 40000
  daily-cost:
    level-1: 50 # Charged every TownyNewDay.
    level-2: 100
    level-3: 200
    level-4: 400
  stipend:
    level-1: 250 # The cost to "re-hire" a bailiff if they haven't been paid their daily cost.
    level-2: 500
    level-3: 1000
    level-4: 2000
portmaster:
  allowed-biomes: # A list of biomes, at least one of which has to be present in the chunk that a port is created in.
    - COLD_OCEAN
    - DEEP_COLD_OCEAN
    - DEEP_FROZEN_OCEAN
    - DEEP_LUKEWARM_OCEAN
    - DEEP_OCEAN
    - DEEP_WARM_OCEAN
    - FROZEN_OCEAN
    - FROZEN_OCEAN
    - LUKEWARM_OCEAN
    - OCEAN
    - WARM_OCEAN
  upgrade-cost:
    level-1: 12500
    level-2: 22500
    level-3: 42500
    level-4: 70000
  daily-cost:
    level-1: 125
    level-2: 225
    level-3: 425
    level-4: 700
  stipend:
    level-1: 625
    level-2: 1125
    level-3: 2125
    level-4: 3500
stablemaster:
  upgrade-cost:
    level-1: 11000
    level-2: 20000
    level-3: 40000
  daily-cost:
    level-1: 150
    level-2: 220
    level-3: 400
  stipend:
    level-1: 750
    level-2: 1100
    level-3: 2000
guardcaptain:
  count:
    level-1: 1
    level-2: 2
    level-3: 4
    level-4: 6
  wander-range:
    level-1: 6
    level-2: 9
    level-3: 12
    level-4: 16
  upgrade-cost:
    level-1: 12500
    level-2: 25000
    level-3: 50000
    level-4: 100000
  daily-cost:
    level-1: 125
    level-2: 250
    level-3: 500
    level-4: 1000
  stipend:
    level-1: 600
    level-2: 1250
    level-3: 2500
    level-4: 5000
guard:
  respawn-time: 12000 # In ticks.
  health: 20.0
  melee-range:
    min: 5
    max: 20
    default: 10
  ranged-range:
    min: 5
    max: 40
    default: 20
  chase-range:
    min: 5
    max: 40
    default: 20