# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"
bailiff:
  claims:
    level-1: 20 # Additional claims added by the bailiff.
    level-2: 40
    level-3: 60
  upgrade-cost:
    level-1: 200000 # Cost to hire bailiff.
    level-2: 300000
    level-3: 400000
treasurer:
  limit:
    level-0: 120000 # Town bank limit without a treasurer.
    level-1: 170000 # Town bank limit with a level 1 treasurer.
    level-2: 200000
    level-3: 250000
    level-4: 300000
    level-5: 350000
    level-6: 400000
  upgrade-cost:
    level-1: 90000
    level-2: 120000
    level-3: 150000
    level-4: 180000
    level-5: 210000
    level-6: 240000
  daily-cost:
    level-1: 900 # Charged every TownyNewDay.
    level-2: 1200
    level-3: 1500
    level-4: 1800
    level-5: 2100
    level-6: 2400
  stipend:
    level-1: 4500 # The cost to "re-hire" a bailiff if they haven't been paid their daily cost.
    level-2: 6000
    level-3: 7500
    level-4: 9000
    level-5: 10500
    level-6: 12000
portmaster:
  allowed-biomes: # A list of biomes, at least one of which has to be present in the chunk that a port is created in.
    - COLD_OCEAN
    - DEEP_COLD_OCEAN
    - DEEP_FROZEN_OCEAN
    - DEEP_LUKEWARM_OCEAN
    - DEEP_OCEAN
    - DEEP_WARM_OCEAN
    - FROZEN_OCEAN
    - FROZEN_OCEAN
    - LUKEWARM_OCEAN
    - OCEAN
    - WARM_OCEAN
  upgrade-cost:
    level-1: 180000
    level-2: 240000
    level-3: 300000
    level-4: 360000
  daily-cost:
    level-1: 1800
    level-2: 2400
    level-3: 3000
    level-4: 3600
  stipend:
    level-1: 9000
    level-2: 12000
    level-3: 15000
    level-4: 18000
stablemaster:
  upgrade-cost:
    level-1: 160000
    level-2: 220000
    level-3: 280000
  daily-cost:
    level-1: 1600
    level-2: 2200
    level-3: 2800
  stipend:
    level-1: 8000
    level-2: 11000
    level-3: 14000